export const countryCode = [
  { name: 'Albania', alpha2: 'AL' },
  { name: 'Algeria', alpha2: 'DZ' },
  { name: 'Andorra', alpha2: 'AD' },
  { name: 'Argentina', alpha2: 'AR' },
  { name: 'Australia', alpha2: 'AU' },
  { name: 'Austria', alpha2: 'AT' },
  { name: 'Belgium', alpha2: 'BE' },
  { name: 'Brazil', alpha2: 'BR' },
  { name: 'Bulgaria', alpha2: 'BG' },
  { name: 'Canada', alpha2: 'CA' },
  { name: 'Cape Verde', alpha2: '	CV' },
  { name: 'China', alpha2: 'CN' },
  { name: 'Colombia', alpha2: 'CO' },
  { name: 'Costa Rica', alpha2: 'CR' },
  { name: 'Croatia', alpha2: 'HR' },
  { name: 'Cuba', alpha2: 'CU' },
  { name: 'Czech Republic', alpha2: 'CZ' },
  { name: 'Denmark', alpha2: 'DK' },
  { name: 'Dominican Republic', alpha2: 'DO' },
  { name: 'Ecuador', alpha2: 'EC' },
  { name: 'Egypt', alpha2: 'EG' },
  { name: 'El Salvador', alpha2: 'SV' },
  { name: 'Equatorial Guinea', alpha2: 'GQ' },
  { name: 'Estonia', alpha2: 'EE' },
  { name: 'Finland', alpha2: 'FI' },
  { name: 'France', alpha2: 'FR' },
  { name: 'Georgia', alpha2: 'GE' },
  { name: 'Germany', alpha2: 'DE' },
  { name: 'Gibraltar', alpha2: 'GI' },
  { name: 'Greece', alpha2: 'GR' },
  { name: 'Guatemala', alpha2: 'GT' },
  { name: 'Honduras', alpha2: 'HN' },
  { name: 'Hong Kong', alpha2: 'HK' },
  { name: 'Hungary	', alpha2: 'HU' },
  { name: 'Iceland', alpha2: 'IS' },
  { name: 'India', alpha2: 'IN' },
  { name: 'Indonesia', alpha2: 'ID' },
  { name: 'Ireland', alpha2: 'IE' },
  { name: 'Israel', alpha2: 'IL' },
  { name: 'Italy', alpha2: 'IT' },
  { name: 'Jamaica', alpha2: 'JM' },
  { name: 'Japan', alpha2: 'JP' },
  { name: 'Korea', alpha2: 'KR' },
  { name: 'Latvia', alpha2: 'LV' },
  { name: 'Lebanon', alpha2: 'LB' },
  { name: 'Liechtenstein', alpha2: 'LI' },
  { name: 'Lithuania', alpha2: 'LT' },
  { name: 'Luxembourg', alpha2: 'LU' },
  { name: 'Malaysia', alpha2: 'MY' },
  { name: 'Maldives', alpha2: 'MV' },
  { name: 'Mali', alpha2: 'ML' },
  { name: 'Malta', alpha2: 'MT' },
  { name: 'Mexico', alpha2: 'MX' },
  { name: 'Morocco', alpha2: 'MA' },
  { name: 'Mozambique', alpha2: 'MZ' },
  { name: 'Myanmar', alpha2: 'MM' },
  { name: 'Netherlands', alpha2: 'NL' },
  { name: 'New Caledonia', alpha2: 'NC' },
  { name: 'New Zealand', alpha2: 'NZ' },
  { name: 'Nicaragua', alpha2: 'NI' },
  { name: 'Niger', alpha2: 'NE' },
  { name: 'Nigeria', alpha2: 'NG' },
  { name: 'Norway', alpha2: 'NO' },
  { name: 'Panama', alpha2: 'PA' },
  { name: 'Peru', alpha2: 'PE' },
  { name: 'Philippines', alpha2: 'PH' },
  { name: 'Poland', alpha2: 'PL' },
  { name: 'Portugal', alpha2: 'PT' },
  { name: 'Puerto Rico', alpha2: 'PR' },
  { name: 'Qatar', alpha2: 'QA' },
  { name: 'Romania', alpha2: 'RO' },
  { name: 'Russian Federation', alpha2: 'RU' },
  { name: 'Saudi Arabia', alpha2: 'SA' },
  { name: 'Senegal', alpha2: 'SN' },
  { name: 'Serbia', alpha2: 'RS' },
  { name: 'Singapore', alpha2: 'SG' },
  { name: 'Slovakia', alpha2: 'SK' },
  { name: 'Slovenia', alpha2: 'SI' },
  { name: 'South Africa', alpha2: 'ZA' },
  { name: 'Spain', alpha2: 'ES' },
  { name: 'Sri Lanka', alpha2: 'LK' },
  { name: 'Sudan', alpha2: 'SD' },
  { name: 'Sweden', alpha2: 'SE' },
  { name: 'Switzerland', alpha2: 'CH' },
  { name: 'Thailand', alpha2: 'TH' },
  { name: 'Tonga', alpha2: 'TO' },
  { name: 'Tunisia', alpha2: 'TN' },
  { name: 'Turkey', alpha2: 'TR' },
  { name: 'Ukraine', alpha2: 'UA' },
  { name: 'United Arab Emirates', alpha2: 'AE' },
  { name: 'United Kingdom', alpha2: 'GB' },
  { name: 'United States', alpha2: 'US' },
  { name: 'Uruguay', alpha2: 'UY' },
  { name: 'Uzbekistan', alpha2: 'UZ' },
  { name: 'Vanuatu', alpha2: 'VU' },
  { name: 'Venezuela', alpha2: 'VE' },
  { name: 'Viet Nam', alpha2: 'VN' },
  { name: 'Yemen', alpha2: 'YE' },
  { name: 'Zambia', alpha2: 'ZM' },
  { name: 'Zimbabwe', alpha2: 'ZW' },
];